Playstation Classic modified files.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -252,11 +252,11 @@ arm*)
   if [ "x$fpu" != "x" ]; then
     echo "$CFLAGS" | grep -q -- '-mfpu=' || CFLAGS="$CFLAGS -mfpu=$fpu"
     echo "$ASFLAGS" | grep -q -- '-mfpu=' || ASFLAGS="$ASFLAGS -mfpu=$fpu"
-    floatabi_set_by_gcc=`$CC -v 2>&1 | grep -q -- --with-float= && echo yes` || true
-    if [ "$floatabi_set_by_gcc" != "yes" ]; then
-      echo "$CFLAGS" | grep -q -- '-mfloat-abi=' || CFLAGS="$CFLAGS -mfloat-abi=softfp"
-      echo "$ASFLAGS" | grep -q -- '-mfloat-abi=' || ASFLAGS="$ASFLAGS -mfloat-abi=softfp"
-    fi
+    #floatabi_set_by_gcc=`$CC -v 2>&1 | grep -q -- --with-float= && echo yes` || true
+    #if [ "$floatabi_set_by_gcc" != "yes" ]; then
+      #echo "$CFLAGS" | grep -q -- '-mfloat-abi=' || CFLAGS="$CFLAGS -mfloat-abi=softfp"
+      #echo "$ASFLAGS" | grep -q -- '-mfloat-abi=' || ASFLAGS="$ASFLAGS -mfloat-abi=softfp"
+    #fi
   fi
 
   # must disable thumb as recompiler can't handle it
@@ -402,7 +402,7 @@ if [ "x$sound_drivers" = "x" ]; then
     sound_drivers="$sound_drivers pulseaudio"
     MAIN_LDLIBS="-lpulse $MAIN_LDLIBS"
   fi
-  if [ "$need_sdl" = "yes" ] || check_sdl `sdl-config --cflags --libs`; then
+  if [ "$need_sdl" = "yes" ] || check_sdl `sdl2-config --cflags --libs`; then
     sound_drivers="$sound_drivers sdl"
     need_sdl="yes"
   fi
@@ -421,11 +421,11 @@ else
 fi
 
 if [ "$need_sdl" = "yes" ]; then
-  which sdl-config > /dev/null || \
-    fail "sdl-config is missing; please install libsdl (libsdl1.2-dev)"
-  CFLAGS="$CFLAGS `sdl-config --cflags`"
-  MAIN_LDLIBS="`sdl-config --libs` $MAIN_LDLIBS"
-  check_sdl || fail "please install libsdl (libsdl1.2-dev)"
+  which sdl2-config > /dev/null || \
+    fail "sdl2-config is missing; please install libsdl2"
+  CFLAGS="$CFLAGS `pkg-config --cflags sdl2`"
+  MAIN_LDLIBS="`pkg-config --libs sdl2` $MAIN_LDLIBS"
+  check_sdl || fail "please install libsdl2"
 fi
 
 # check for tslib (only headers needed)
@@ -448,7 +448,7 @@ if [ -d /opt/vc/include -a -d /opt/vc/lib -a "$VIDEOCORE" != "no" ]; then
   if [ -f /opt/vc/lib/libbcm_host.so ]; then
     LDLIBS_GLES="$LDLIBS_GLES -lbcm_host"
   fi
-  need_xlib="yes"
+  need_xlib="no"
   VIDEOCORE="yes"
 fi
 
@@ -531,6 +531,8 @@ echo "tslib support       $have_tslib"
 if [ "$platform" = "generic" ]; then
   echo "OpenGL ES output    $have_gles"
 fi
+
+MAIN_LDLIBS="$MAIN_LDLIBS -lwayland-client -lwayland-egl"
 
 echo "# Automatically generated by configure" > $config_mak
 printf "# Configured with:" >> $config_mak
